In [1]:
#ans 1

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [2]:
#ans 2
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Printing the data type of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Printing the data type of each element in array_list
print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [3]:
#ans 3
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Printing the data type of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Printing the data type of each element in array_list
print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))

# For the new part of the question
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Printing the data type of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Printing the data type of each element in array_list
print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))

# For the new part of the question
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [4]:
#ans 4

import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Finding the shape of num_array
shape = num_array.shape

# Finding the size of num_array
size = num_array.size

print("Shape of num_array:", shape)
print("Size of num_array:", size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [5]:
#ans 5

import numpy as np

zero_matrix = np.zeros((3, 3))

print("3x3 matrix containing zeros:")
print(zero_matrix)


3x3 matrix containing zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
#ans 6

import numpy as np

identity_matrix = np.identity(5)

print("5x5 identity matrix:")
print(identity_matrix)


import numpy as np

identity_matrix = np.eye(5)

print("5x5 identity matrix:")
print(identity_matrix)


5x5 identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
5x5 identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
